channels:
  - defaults
  - r
dependencies:
  - python=3
  - numpy
  - scipy
  - pandas
  - networkx
  - matplotlib
  - sympy
  - scikit-learn
  - statsmodels
  - pydot
  - seaborn
  - pygraphviz
  - rpy2
  - pip
  - pip:
    - graphviz
    - econml
